/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/usr/lib/nim -o /home/lowkey/go/src/github.com/LowkeyCoding/nim/BFC/src/nimcache/BFC_BFC.o /home/lowkey/go/src/github.com/LowkeyCoding/nim/BFC/src/nimcache/BFC_BFC.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NI tyArray_9cc9aPiDa8VaWjVcFLabEDZQ[256];
typedef NimStringDesc* tyArray_yt5VDPNtUGx9cBkOVakHwdQ[6];
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
N_NIMCALL(void, initSkipTable_zH9bR9aeRX1zXB71hz1e3rJw)(NI* a, NimStringDesc* sub);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, stringFind_L0xlQZF4Gjx7rBOB7n9bfzQ)(tyArray_9cc9aPiDa8VaWjVcFLabEDZQ skibTable, NimStringDesc* str, NimStringDesc* sub, NI start, NI last);
N_NIMCALL(NI, find_w8aIjbfjmB8KnU6tI9aMffg)(NimStringDesc* str, NimStringDesc* sub);
N_NIMCALL(NIM_BOOL, match_FCjZ69cFX5YNEsn34aJIBlQ)(NimStringDesc* str, NimStringDesc* sub);
N_NIMCALL(NimStringDesc*, remove_m8aNZgYY8sFB9b9aVWepru3Q)(NimStringDesc* str, NimStringDesc* sub);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, removeUntil_3P89bFSkd13FW8aZqI3k9cbQ)(NimStringDesc* str, NimStringDesc* SOS, NimStringDesc* EOS);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, strip_EYOGEYft0ixrprKphY1KfQ)(NimStringDesc* str);
N_NIMCALL(NimStringDesc*, addString_Cr4ch2JsB1P6pw8L0cs9bwQ)(NimStringDesc* chr, NI times);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, compare_hXb79btr1I9al86CMLvrSwkw)(NIM_CHAR word);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, lexicalAnalyzer_eCipD49bBoR7XjzCwo6ye8w)(NimStringDesc* code);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, generateCodeC_eCipD49bBoR7XjzCwo6ye8w_2)(NimStringDesc* code);
N_NIMCALL(NimStringDesc*, generateCode_MOnda5xe8q9bWBsnOA9afp9aA)(NimStringDesc* code, NimStringDesc* lang);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_NIMCALL(void, writeToFile_O8j2V6DeDme1O9crQcbqBQg)(NimStringDesc* code, NimStringDesc* fileName);
N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_NIMCALL(NimStringDesc*, readFile_3HW0pLTpyB6rNH9c9bTGJJsA)(NimStringDesc* fileName);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(NIM_BOOL, readLine_sO1bQXVRA6RP9cdYJXNKeSw)(FILE* f, NimStringDesc** line);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_569c4PmJWUpENBqMXK119bZQ_63)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, TM_569c4PmJWUpENBqMXK119bZQ_64)(void);
static N_NIMCALL(void, TM_569c4PmJWUpENBqMXK119bZQ_65)(void);
N_NIMCALL(NI, paramCount_T74rCHY8RMV0X07YnKmggw)(void);
N_NIMCALL(NimStringDesc*, paramStr_eYicl3uwirn1ppNz7OCowg)(NI i);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, BFCDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NimStringDesc* inputFileName_zB9b9b52qh3XkFGjYLZE2juA;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NimStringDesc* outputFileName_ZhcyHRBNyFnZRHhCh8XN6Q;
NimStringDesc* lang_mHGi2iZeE3sD2KmUf2Yh7Q;
NI i_y9c9bTrpgLVFY29bwEqnXhzCg;
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_26, " ", 1);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_27, "\011", 1);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_28, "\013", 1);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_29, "\015", 1);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_30, "\012", 1);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_31, "\014", 1);
NIM_CONST tyArray_yt5VDPNtUGx9cBkOVakHwdQ TM_569c4PmJWUpENBqMXK119bZQ_25 = {((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_26),
((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_27),
((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_28),
((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_29),
((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_30),
((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_31)}
;
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_33, "", 0);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_34, "  ", 2);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_36, "ADD-PTR", 7);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_37, "SUB-PTR", 7);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_38, "ADD", 3);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_39, "SUB", 3);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_40, "INPUT", 5);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_41, "PRINT", 5);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_42, "START", 5);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_43, "END", 3);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_44, " ERROR", 6);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_45, "//", 2);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_46, "ERROR", 5);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_48, "len(a) == L string modified while iterating over it", 51);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_49, "#include <stdio.h>\012char tape[2147483647/2];\012char *ptr;\012int main"
"() {\012  ptr=tape;\012", 80);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_50, "ptr++;\012", 7);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_51, "ptr--;\012", 7);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_52, "(*ptr)++;\012", 10);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_53, "(*ptr)--;\012", 10);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_54, "putchar(*ptr);\012", 15);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_55, "*ptr=getchar();\012", 16);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_56, "while (*ptr){\012", 14);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_58, "}\012", 2);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_61, "return 1;\012}", 11);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_62, "C", 1);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_66, "--input", 7);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_67, "-i", 2);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_68, "--output", 8);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_69, "-o", 2);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_70, "--lang", 6);
STRING_LITERAL(TM_569c4PmJWUpENBqMXK119bZQ_71, "-l", 2);

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, initSkipTable_zH9bR9aeRX1zXB71hz1e3rJw)(NI* a, NimStringDesc* sub) {
	NI m;
	NI i;
	nimfr_("initSkipTable", "BFC.nim");
	nimln_(6, "BFC.nim");
	m = (sub ? sub->Sup.len : 0);
	nimln_(7, "BFC.nim");
	i = ((NI) 0);
	{
		nimln_(8, "BFC.nim");
		while (1) {
			NI TM_569c4PmJWUpENBqMXK119bZQ_2;
			NI TM_569c4PmJWUpENBqMXK119bZQ_3;
			NI TM_569c4PmJWUpENBqMXK119bZQ_4;
			NI TM_569c4PmJWUpENBqMXK119bZQ_5;
			NI TM_569c4PmJWUpENBqMXK119bZQ_6;
			NI TM_569c4PmJWUpENBqMXK119bZQ_7;
			NI TM_569c4PmJWUpENBqMXK119bZQ_8;
			NI TM_569c4PmJWUpENBqMXK119bZQ_9;
			NI TM_569c4PmJWUpENBqMXK119bZQ_10;
			if (!(i <= ((NI) 248))) goto LA2;
			nimln_(9, "BFC.nim");
			TM_569c4PmJWUpENBqMXK119bZQ_2 = addInt(i, ((NI) 0));
			a[(((NU8)(((NIM_CHAR) (((NI)chckRange((NI)(TM_569c4PmJWUpENBqMXK119bZQ_2), ((NI) 0), ((NI) 255))))))))- 0] = m;
			nimln_(10, "BFC.nim");
			TM_569c4PmJWUpENBqMXK119bZQ_3 = addInt(i, ((NI) 1));
			a[(((NU8)(((NIM_CHAR) (((NI)chckRange((NI)(TM_569c4PmJWUpENBqMXK119bZQ_3), ((NI) 0), ((NI) 255))))))))- 0] = m;
			nimln_(11, "BFC.nim");
			TM_569c4PmJWUpENBqMXK119bZQ_4 = addInt(i, ((NI) 2));
			a[(((NU8)(((NIM_CHAR) (((NI)chckRange((NI)(TM_569c4PmJWUpENBqMXK119bZQ_4), ((NI) 0), ((NI) 255))))))))- 0] = m;
			nimln_(12, "BFC.nim");
			TM_569c4PmJWUpENBqMXK119bZQ_5 = addInt(i, ((NI) 3));
			a[(((NU8)(((NIM_CHAR) (((NI)chckRange((NI)(TM_569c4PmJWUpENBqMXK119bZQ_5), ((NI) 0), ((NI) 255))))))))- 0] = m;
			nimln_(13, "BFC.nim");
			TM_569c4PmJWUpENBqMXK119bZQ_6 = addInt(i, ((NI) 4));
			a[(((NU8)(((NIM_CHAR) (((NI)chckRange((NI)(TM_569c4PmJWUpENBqMXK119bZQ_6), ((NI) 0), ((NI) 255))))))))- 0] = m;
			nimln_(14, "BFC.nim");
			TM_569c4PmJWUpENBqMXK119bZQ_7 = addInt(i, ((NI) 5));
			a[(((NU8)(((NIM_CHAR) (((NI)chckRange((NI)(TM_569c4PmJWUpENBqMXK119bZQ_7), ((NI) 0), ((NI) 255))))))))- 0] = m;
			nimln_(15, "BFC.nim");
			TM_569c4PmJWUpENBqMXK119bZQ_8 = addInt(i, ((NI) 6));
			a[(((NU8)(((NIM_CHAR) (((NI)chckRange((NI)(TM_569c4PmJWUpENBqMXK119bZQ_8), ((NI) 0), ((NI) 255))))))))- 0] = m;
			nimln_(16, "BFC.nim");
			TM_569c4PmJWUpENBqMXK119bZQ_9 = addInt(i, ((NI) 7));
			a[(((NU8)(((NIM_CHAR) (((NI)chckRange((NI)(TM_569c4PmJWUpENBqMXK119bZQ_9), ((NI) 0), ((NI) 255))))))))- 0] = m;
			nimln_(17, "BFC.nim");
			TM_569c4PmJWUpENBqMXK119bZQ_10 = addInt(i, ((NI) 8));
			i = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_10);
		} LA2: ;
	}
	{
		NI i_2;
		NI colontmp_;
		NI TM_569c4PmJWUpENBqMXK119bZQ_11;
		NI i_3;
		i_2 = (NI)0;
		colontmp_ = (NI)0;
		nimln_(18, "BFC.nim");
		TM_569c4PmJWUpENBqMXK119bZQ_11 = subInt(m, ((NI) 1));
		colontmp_ = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_11);
		nimln_(3832, "system.nim");
		i_3 = ((NI) 0);
		{
			nimln_(3833, "system.nim");
			while (1) {
				NI TM_569c4PmJWUpENBqMXK119bZQ_12;
				NI TM_569c4PmJWUpENBqMXK119bZQ_13;
				NI TM_569c4PmJWUpENBqMXK119bZQ_14;
				if (!(i_3 < colontmp_)) goto LA5;
				nimln_(3834, "system.nim");
				i_2 = i_3;
				if ((NU)(i_2) > (NU)(sub->Sup.len)) raiseIndexError();
				nimln_(19, "BFC.nim");
				TM_569c4PmJWUpENBqMXK119bZQ_12 = subInt(m, ((NI) 1));
				TM_569c4PmJWUpENBqMXK119bZQ_13 = subInt((NI)(TM_569c4PmJWUpENBqMXK119bZQ_12), i_2);
				a[(((NU8)(sub->data[i_2])))- 0] = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_13);
				nimln_(3835, "system.nim");
				TM_569c4PmJWUpENBqMXK119bZQ_14 = addInt(i_3, ((NI) 1));
				i_3 = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_14);
			} LA5: ;
		}
	}
	popFrame();
}

N_NIMCALL(NI, stringFind_L0xlQZF4Gjx7rBOB7n9bfzQ)(tyArray_9cc9aPiDa8VaWjVcFLabEDZQ skibTable, NimStringDesc* str, NimStringDesc* sub, NI start, NI last) {
	NI result;
	NI last_2;
	NI sLen;
	NI TM_569c4PmJWUpENBqMXK119bZQ_15;
	NI TM_569c4PmJWUpENBqMXK119bZQ_16;
	NI subLast;
	NI TM_569c4PmJWUpENBqMXK119bZQ_17;
	NI skip;
	nimfr_("stringFind", "BFC.nim");
{	result = (NI)0;
	nimln_(22, "BFC.nim");
	{
		if (!(last == ((NI) 0))) goto LA3_;
		last_2 = (str ? (str->Sup.len-1) : -1);
	}
	goto LA1_;
	LA3_: ;
	{
		last_2 = last;
	}
	LA1_: ;
	nimln_(23, "BFC.nim");
	TM_569c4PmJWUpENBqMXK119bZQ_15 = subInt(last_2, ((NI) (start)));
	TM_569c4PmJWUpENBqMXK119bZQ_16 = addInt((NI)(TM_569c4PmJWUpENBqMXK119bZQ_15), ((NI) 1));
	sLen = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_16);
	nimln_(24, "BFC.nim");
	TM_569c4PmJWUpENBqMXK119bZQ_17 = subInt((sub ? sub->Sup.len : 0), ((NI) 1));
	subLast = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_17);
	nimln_(26, "BFC.nim");
	{
		if (!(subLast == ((NI) -1))) goto LA8_;
		nimln_(27, "BFC.nim");
		result = ((NI) (start));
		goto BeforeRet_;
	}
	LA8_: ;
	nimln_(29, "BFC.nim");
	skip = start;
	{
		nimln_(31, "BFC.nim");
		while (1) {
			NI TM_569c4PmJWUpENBqMXK119bZQ_18;
			NI i;
			NI TM_569c4PmJWUpENBqMXK119bZQ_21;
			NI TM_569c4PmJWUpENBqMXK119bZQ_22;
			TM_569c4PmJWUpENBqMXK119bZQ_18 = subInt(last_2, ((NI) (skip)));
			if (!(subLast <= (NI)(TM_569c4PmJWUpENBqMXK119bZQ_18))) goto LA11;
			nimln_(32, "BFC.nim");
			i = subLast;
			{
				nimln_(33, "BFC.nim");
				while (1) {
					NI TM_569c4PmJWUpENBqMXK119bZQ_19;
					NI TM_569c4PmJWUpENBqMXK119bZQ_20;
					TM_569c4PmJWUpENBqMXK119bZQ_19 = addInt(((NI) (skip)), i);
					if ((NU)((NI)(TM_569c4PmJWUpENBqMXK119bZQ_19)) > (NU)(str->Sup.len)) raiseIndexError();
					if ((NU)(i) > (NU)(sub->Sup.len)) raiseIndexError();
					if (!((NU8)(str->data[(NI)(TM_569c4PmJWUpENBqMXK119bZQ_19)]) == (NU8)(sub->data[i]))) goto LA13;
					nimln_(34, "BFC.nim");
					{
						if (!(i == ((NI) 0))) goto LA16_;
						nimln_(35, "BFC.nim");
						result = ((NI) (skip));
						goto BeforeRet_;
					}
					LA16_: ;
					nimln_(36, "BFC.nim");
					TM_569c4PmJWUpENBqMXK119bZQ_20 = subInt(i, ((NI) 1));
					i = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_20);
				} LA13: ;
			}
			nimln_(37, "BFC.nim");
			TM_569c4PmJWUpENBqMXK119bZQ_21 = addInt(((NI) (skip)), subLast);
			if ((NU)((NI)(TM_569c4PmJWUpENBqMXK119bZQ_21)) > (NU)(str->Sup.len)) raiseIndexError();
			TM_569c4PmJWUpENBqMXK119bZQ_22 = addInt(skip, skibTable[(((NU8)(str->data[(NI)(TM_569c4PmJWUpENBqMXK119bZQ_21)])))- 0]);
			if (TM_569c4PmJWUpENBqMXK119bZQ_22 < 0 || TM_569c4PmJWUpENBqMXK119bZQ_22 > IL64(9223372036854775807)) raiseOverflow();
			skip = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_22);
		} LA11: ;
	}
	nimln_(39, "BFC.nim");
	result = ((NI) -1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, find_w8aIjbfjmB8KnU6tI9aMffg)(NimStringDesc* str, NimStringDesc* sub) {
	NI result;
	tyArray_9cc9aPiDa8VaWjVcFLabEDZQ skipTable;
	nimfr_("find", "BFC.nim");
{	result = (NI)0;
	nimln_(42, "BFC.nim");
	initSkipTable_zH9bR9aeRX1zXB71hz1e3rJw(skipTable, sub);
	nimln_(43, "BFC.nim");
	result = stringFind_L0xlQZF4Gjx7rBOB7n9bfzQ(skipTable, str, sub, ((NI) 0), ((NI) 0));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, match_FCjZ69cFX5YNEsn34aJIBlQ)(NimStringDesc* str, NimStringDesc* sub) {
	NIM_BOOL result;
	tyArray_9cc9aPiDa8VaWjVcFLabEDZQ skipTable;
	nimfr_("match", "BFC.nim");
{	result = (NIM_BOOL)0;
	nimln_(46, "BFC.nim");
	initSkipTable_zH9bR9aeRX1zXB71hz1e3rJw(skipTable, sub);
	nimln_(47, "BFC.nim");
	{
		NI T3_;
		nimln_(378, "system.nim");
		nimln_(47, "BFC.nim");
		T3_ = (NI)0;
		T3_ = stringFind_L0xlQZF4Gjx7rBOB7n9bfzQ(skipTable, str, sub, ((NI) 0), ((NI) 0));
		if (!!((T3_ == ((NI) -1)))) goto LA4_;
		nimln_(48, "BFC.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA4_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, remove_m8aNZgYY8sFB9b9aVWepru3Q)(NimStringDesc* str, NimStringDesc* sub) {
	NimStringDesc* result;
	NimStringDesc* str_2;
	NI check;
	nimfr_("remove", "BFC.nim");
{	result = (NimStringDesc*)0;
	nimln_(50, "BFC.nim");
	str_2 = copyString(str);
	nimln_(51, "BFC.nim");
	check = find_w8aIjbfjmB8KnU6tI9aMffg(str_2, sub);
	{
		nimln_(52, "BFC.nim");
		while (1) {
			NimStringDesc* T3_;
			NI T4_;
			NI TM_569c4PmJWUpENBqMXK119bZQ_23;
			NimStringDesc* T5_;
			NI T6_;
			NI TM_569c4PmJWUpENBqMXK119bZQ_24;
			NimStringDesc* T7_;
			nimln_(53, "BFC.nim");
			T3_ = (NimStringDesc*)0;
			T4_ = (NI)0;
			T4_ = find_w8aIjbfjmB8KnU6tI9aMffg(str_2, sub);
			TM_569c4PmJWUpENBqMXK119bZQ_23 = subInt(T4_, ((NI) 1));
			T5_ = (NimStringDesc*)0;
			T5_ = copyStrLast(str_2, ((NI) 0), (NI)(TM_569c4PmJWUpENBqMXK119bZQ_23));
			T6_ = (NI)0;
			T6_ = find_w8aIjbfjmB8KnU6tI9aMffg(str_2, sub);
			TM_569c4PmJWUpENBqMXK119bZQ_24 = addInt(T6_, (sub ? sub->Sup.len : 0));
			T7_ = (NimStringDesc*)0;
			T7_ = copyStrLast(str_2, (NI)(TM_569c4PmJWUpENBqMXK119bZQ_24), (str_2 ? str_2->Sup.len : 0));
			T3_ = rawNewString(T5_->Sup.len + T7_->Sup.len + 0);
appendString(T3_, T5_);
appendString(T3_, T7_);
			str_2 = T3_;
			nimln_(54, "BFC.nim");
			check = find_w8aIjbfjmB8KnU6tI9aMffg(str_2, sub);
			nimln_(55, "BFC.nim");
			{
				if (!(check == ((NI) -1))) goto LA10_;
				nimln_(56, "BFC.nim");
				result = copyString(str_2);
				goto BeforeRet_;
			}
			LA10_: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, removeUntil_3P89bFSkd13FW8aZqI3k9cbQ)(NimStringDesc* str, NimStringDesc* SOS, NimStringDesc* EOS) {
	NimStringDesc* result;
	NimStringDesc* str_2;
	NI strStart;
	NI strEnd;
	nimfr_("removeUntil", "BFC.nim");
{	result = (NimStringDesc*)0;
	nimln_(58, "BFC.nim");
	str_2 = copyString(str);
	nimln_(59, "BFC.nim");
	strStart = find_w8aIjbfjmB8KnU6tI9aMffg(str_2, SOS);
	nimln_(60, "BFC.nim");
	strEnd = find_w8aIjbfjmB8KnU6tI9aMffg(str_2, EOS);
	{
		nimln_(61, "BFC.nim");
		while (1) {
			NimStringDesc* T7_;
			NimStringDesc* T8_;
			NimStringDesc* T9_;
			nimln_(62, "BFC.nim");
			{
				if (!(strStart == ((NI) -1))) goto LA5_;
				nimln_(63, "BFC.nim");
				result = copyString(str_2);
				goto BeforeRet_;
			}
			LA5_: ;
			nimln_(64, "BFC.nim");
			T7_ = (NimStringDesc*)0;
			T7_ = copyStrLast(str_2, strStart, strEnd);
			str_2 = remove_m8aNZgYY8sFB9b9aVWepru3Q(str_2, T7_);
			nimln_(65, "BFC.nim");
			strStart = find_w8aIjbfjmB8KnU6tI9aMffg(str_2, SOS);
			nimln_(66, "BFC.nim");
			strEnd = find_w8aIjbfjmB8KnU6tI9aMffg(str_2, EOS);
			nimln_(67, "BFC.nim");
			T8_ = (NimStringDesc*)0;
			T8_ = nimIntToStr(strStart);
			printf("%s\012", T8_? (T8_)->data:"nil");
			fflush(stdout);
			nimln_(68, "BFC.nim");
			T9_ = (NimStringDesc*)0;
			T9_ = nimIntToStr(strEnd);
			printf("%s\012", T9_? (T9_)->data:"nil");
			fflush(stdout);
			nimln_(69, "BFC.nim");
			{
				if (!(strEnd == ((NI) -1))) goto LA12_;
				nimln_(70, "BFC.nim");
				strEnd = (str_2 ? str_2->Sup.len : 0);
			}
			LA12_: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, strip_EYOGEYft0ixrprKphY1KfQ)(NimStringDesc* str) {
	NimStringDesc* result;
	tyArray_yt5VDPNtUGx9cBkOVakHwdQ whitespaces;
	NimStringDesc* str_2;
	nimfr_("strip", "BFC.nim");
{	result = (NimStringDesc*)0;
	memset((void*)whitespaces, 0, sizeof(whitespaces));
	nimln_(72, "BFC.nim");
	memcpy((void*)whitespaces, (NIM_CONST void*)TM_569c4PmJWUpENBqMXK119bZQ_25, sizeof(whitespaces));
	nimln_(73, "BFC.nim");
	str_2 = copyString(str);
	{
		NimStringDesc* whitespace;
		NI i;
		whitespace = (NimStringDesc*)0;
		nimln_(2092, "system.nim");
		i = ((NI) 0);
		nimln_(2093, "system.nim");
		{
			if (!(((NI) (i)) <= ((NI) 5))) goto LA4_;
			{
				nimln_(2094, "system.nim");
				while (1) {
					NI TM_569c4PmJWUpENBqMXK119bZQ_32;
					nimln_(2095, "system.nim");
					whitespace = copyString(whitespaces[(i)- 0]);
					nimln_(75, "BFC.nim");
					str_2 = remove_m8aNZgYY8sFB9b9aVWepru3Q(str_2, whitespace);
					nimln_(2096, "system.nim");
					{
						if (!(((NI) 5) <= ((NI) (i)))) goto LA10_;
						goto LA6;
					}
					LA10_: ;
					nimln_(2097, "system.nim");
					TM_569c4PmJWUpENBqMXK119bZQ_32 = addInt(i, ((NI) 1));
					if (TM_569c4PmJWUpENBqMXK119bZQ_32 < 0 || TM_569c4PmJWUpENBqMXK119bZQ_32 > 5) raiseOverflow();
					i = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_32);
				}
			} LA6: ;
		}
		LA4_: ;
	}
	nimln_(76, "BFC.nim");
	result = copyString(str_2);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, addString_Cr4ch2JsB1P6pw8L0cs9bwQ)(NimStringDesc* chr, NI times) {
	NimStringDesc* result;
	NimStringDesc* result_2;
	nimfr_("addString", "BFC.nim");
{	result = (NimStringDesc*)0;
	nimln_(78, "BFC.nim");
	result_2 = copyString(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_33));
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(1986, "system.nim");
		res = ((NI) 1);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NI TM_569c4PmJWUpENBqMXK119bZQ_35;
				if (!(res <= times)) goto LA3;
				nimln_(1988, "system.nim");
				i = res;
				nimln_(80, "BFC.nim");
				result_2 = resizeString(result_2, 2);
appendString(result_2, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_34));
				nimln_(1989, "system.nim");
				TM_569c4PmJWUpENBqMXK119bZQ_35 = addInt(res, ((NI) 1));
				res = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_35);
			} LA3: ;
		}
	}
	nimln_(81, "BFC.nim");
	result = copyString(result_2);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(NimStringDesc*, compare_hXb79btr1I9al86CMLvrSwkw)(NIM_CHAR word) {
	NimStringDesc* result;
	nimfr_("compare", "BFC.nim");
{	result = (NimStringDesc*)0;
	nimln_(84, "BFC.nim");
	switch (((NU8)(word))) {
	case 62:
	{
		nimln_(86, "BFC.nim");
		result = copyString(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_36));
		goto BeforeRet_;
	}
	break;
	case 60:
	{
		nimln_(88, "BFC.nim");
		result = copyString(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_37));
		goto BeforeRet_;
	}
	break;
	case 43:
	{
		nimln_(90, "BFC.nim");
		result = copyString(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_38));
		goto BeforeRet_;
	}
	break;
	case 45:
	{
		nimln_(92, "BFC.nim");
		result = copyString(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_39));
		goto BeforeRet_;
	}
	break;
	case 44:
	{
		nimln_(94, "BFC.nim");
		result = copyString(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_40));
		goto BeforeRet_;
	}
	break;
	case 46:
	{
		nimln_(96, "BFC.nim");
		result = copyString(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_41));
		goto BeforeRet_;
	}
	break;
	case 91:
	{
		nimln_(98, "BFC.nim");
		result = copyString(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_42));
		goto BeforeRet_;
	}
	break;
	case 93:
	{
		nimln_(100, "BFC.nim");
		result = copyString(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_43));
		goto BeforeRet_;
	}
	break;
	default:
	{
		NimStringDesc* T10_;
		nimln_(102, "BFC.nim");
		T10_ = (NimStringDesc*)0;
		T10_ = rawNewString(7);
appendChar(T10_, word);
appendString(T10_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_44));
		result = T10_;
		goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, lexicalAnalyzer_eCipD49bBoR7XjzCwo6ye8w)(NimStringDesc* code) {
	NimStringDesc* result;
	NimStringDesc* result_2;
	NimStringDesc* code_2;
	nimfr_("lexicalAnalyzer", "BFC.nim");
{	result = (NimStringDesc*)0;
	nimln_(105, "BFC.nim");
	result_2 = copyString(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_33));
	nimln_(106, "BFC.nim");
	code_2 = removeUntil_3P89bFSkd13FW8aZqI3k9cbQ(code, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_45), ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_30));
	nimln_(107, "BFC.nim");
	code_2 = strip_EYOGEYft0ixrprKphY1KfQ(code_2);
	{
		NIM_CHAR word;
		NI i;
		NI L;
		word = (NIM_CHAR)0;
		nimln_(3657, "system.nim");
		i = ((NI) 0);
		nimln_(3658, "system.nim");
		L = (code_2 ? code_2->Sup.len : 0);
		{
			nimln_(3659, "system.nim");
			while (1) {
				NimStringDesc* comp;
				NI TM_569c4PmJWUpENBqMXK119bZQ_47;
				if (!(i < L)) goto LA3;
				nimln_(3660, "system.nim");
				if ((NU)(i) > (NU)(code_2->Sup.len)) raiseIndexError();
				word = code_2->data[i];
				nimln_(109, "BFC.nim");
				comp = compare_hXb79btr1I9al86CMLvrSwkw(word);
				nimln_(110, "BFC.nim");
				{
					NIM_BOOL T6_;
					T6_ = (NIM_BOOL)0;
					T6_ = match_FCjZ69cFX5YNEsn34aJIBlQ(comp, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_46));
					if (!T6_) goto LA7_;
					nimln_(111, "BFC.nim");
					printf("%s\012", comp? (comp)->data:"nil");
					fflush(stdout);
				}
				goto LA4_;
				LA7_: ;
				{
					NimStringDesc* T10_;
					nimln_(113, "BFC.nim");
					T10_ = (NimStringDesc*)0;
					T10_ = rawNewString(comp->Sup.len + 1);
appendString(T10_, comp);
appendString(T10_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_30));
					result_2 = resizeString(result_2, T10_->Sup.len + 0);
appendString(result_2, T10_);
				}
				LA4_: ;
				nimln_(3661, "system.nim");
				TM_569c4PmJWUpENBqMXK119bZQ_47 = addInt(i, ((NI) 1));
				i = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_47);
				nimln_(3662, "system.nim");
				{
					if (!!(((code_2 ? code_2->Sup.len : 0) == L))) goto LA13_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_48));
				}
				LA13_: ;
			} LA3: ;
		}
	}
	nimln_(114, "BFC.nim");
	result = copyString(result_2);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, generateCodeC_eCipD49bBoR7XjzCwo6ye8w_2)(NimStringDesc* code) {
	NimStringDesc* result;
	NimStringDesc* result_2;
	NI tapLevel;
	NimStringDesc* code_2;
	NimStringDesc* T34_;
	nimfr_("generateCodeC", "BFC.nim");
{	result = (NimStringDesc*)0;
	nimln_(117, "BFC.nim");
	result_2 = copyString(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_49));
	nimln_(118, "BFC.nim");
	tapLevel = ((NI) 1);
	nimln_(119, "BFC.nim");
	code_2 = removeUntil_3P89bFSkd13FW8aZqI3k9cbQ(code, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_45), ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_30));
	nimln_(120, "BFC.nim");
	code_2 = strip_EYOGEYft0ixrprKphY1KfQ(code_2);
	{
		NIM_CHAR word;
		NI i;
		NI L;
		word = (NIM_CHAR)0;
		nimln_(3657, "system.nim");
		i = ((NI) 0);
		nimln_(3658, "system.nim");
		L = (code_2 ? code_2->Sup.len : 0);
		{
			nimln_(3659, "system.nim");
			while (1) {
				NI TM_569c4PmJWUpENBqMXK119bZQ_60;
				if (!(i < L)) goto LA3;
				nimln_(3660, "system.nim");
				if ((NU)(i) > (NU)(code_2->Sup.len)) raiseIndexError();
				word = code_2->data[i];
				nimln_(122, "BFC.nim");
				switch (((NU8)(word))) {
				case 62:
				{
					NimStringDesc* T5_;
					NimStringDesc* T6_;
					nimln_(124, "BFC.nim");
					T5_ = (NimStringDesc*)0;
					T6_ = (NimStringDesc*)0;
					T6_ = addString_Cr4ch2JsB1P6pw8L0cs9bwQ(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_34), tapLevel);
					T5_ = rawNewString(T6_->Sup.len + 7);
appendString(T5_, T6_);
appendString(T5_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_50));
					result_2 = resizeString(result_2, T5_->Sup.len + 0);
appendString(result_2, T5_);
				}
				break;
				case 60:
				{
					NimStringDesc* T8_;
					NimStringDesc* T9_;
					nimln_(126, "BFC.nim");
					T8_ = (NimStringDesc*)0;
					T9_ = (NimStringDesc*)0;
					T9_ = addString_Cr4ch2JsB1P6pw8L0cs9bwQ(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_34), tapLevel);
					T8_ = rawNewString(T9_->Sup.len + 7);
appendString(T8_, T9_);
appendString(T8_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_51));
					result_2 = resizeString(result_2, T8_->Sup.len + 0);
appendString(result_2, T8_);
				}
				break;
				case 43:
				{
					NimStringDesc* T11_;
					NimStringDesc* T12_;
					nimln_(128, "BFC.nim");
					T11_ = (NimStringDesc*)0;
					T12_ = (NimStringDesc*)0;
					T12_ = addString_Cr4ch2JsB1P6pw8L0cs9bwQ(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_34), tapLevel);
					T11_ = rawNewString(T12_->Sup.len + 10);
appendString(T11_, T12_);
appendString(T11_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_52));
					result_2 = resizeString(result_2, T11_->Sup.len + 0);
appendString(result_2, T11_);
				}
				break;
				case 45:
				{
					NimStringDesc* T14_;
					NimStringDesc* T15_;
					nimln_(130, "BFC.nim");
					T14_ = (NimStringDesc*)0;
					T15_ = (NimStringDesc*)0;
					T15_ = addString_Cr4ch2JsB1P6pw8L0cs9bwQ(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_34), tapLevel);
					T14_ = rawNewString(T15_->Sup.len + 10);
appendString(T14_, T15_);
appendString(T14_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_53));
					result_2 = resizeString(result_2, T14_->Sup.len + 0);
appendString(result_2, T14_);
				}
				break;
				case 46:
				{
					NimStringDesc* T17_;
					NimStringDesc* T18_;
					nimln_(132, "BFC.nim");
					T17_ = (NimStringDesc*)0;
					T18_ = (NimStringDesc*)0;
					T18_ = addString_Cr4ch2JsB1P6pw8L0cs9bwQ(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_34), tapLevel);
					T17_ = rawNewString(T18_->Sup.len + 15);
appendString(T17_, T18_);
appendString(T17_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_54));
					result_2 = resizeString(result_2, T17_->Sup.len + 0);
appendString(result_2, T17_);
				}
				break;
				case 44:
				{
					NimStringDesc* T20_;
					NimStringDesc* T21_;
					nimln_(134, "BFC.nim");
					T20_ = (NimStringDesc*)0;
					T21_ = (NimStringDesc*)0;
					T21_ = addString_Cr4ch2JsB1P6pw8L0cs9bwQ(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_34), tapLevel);
					T20_ = rawNewString(T21_->Sup.len + 16);
appendString(T20_, T21_);
appendString(T20_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_55));
					result_2 = resizeString(result_2, T20_->Sup.len + 0);
appendString(result_2, T20_);
				}
				break;
				case 91:
				{
					NimStringDesc* T23_;
					NimStringDesc* T24_;
					NI TM_569c4PmJWUpENBqMXK119bZQ_57;
					nimln_(136, "BFC.nim");
					T23_ = (NimStringDesc*)0;
					T24_ = (NimStringDesc*)0;
					T24_ = addString_Cr4ch2JsB1P6pw8L0cs9bwQ(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_34), tapLevel);
					T23_ = rawNewString(T24_->Sup.len + 14);
appendString(T23_, T24_);
appendString(T23_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_56));
					result_2 = resizeString(result_2, T23_->Sup.len + 0);
appendString(result_2, T23_);
					nimln_(137, "BFC.nim");
					TM_569c4PmJWUpENBqMXK119bZQ_57 = addInt(tapLevel, ((NI) 1));
					tapLevel = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_57);
				}
				break;
				case 93:
				{
					NimStringDesc* T26_;
					NimStringDesc* T27_;
					NI TM_569c4PmJWUpENBqMXK119bZQ_59;
					nimln_(139, "BFC.nim");
					T26_ = (NimStringDesc*)0;
					T27_ = (NimStringDesc*)0;
					T27_ = addString_Cr4ch2JsB1P6pw8L0cs9bwQ(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_34), tapLevel);
					T26_ = rawNewString(T27_->Sup.len + 2);
appendString(T26_, T27_);
appendString(T26_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_58));
					result_2 = resizeString(result_2, T26_->Sup.len + 0);
appendString(result_2, T26_);
					nimln_(140, "BFC.nim");
					TM_569c4PmJWUpENBqMXK119bZQ_59 = subInt(tapLevel, ((NI) 1));
					tapLevel = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_59);
				}
				break;
				default:
				{
					NimStringDesc* T29_;
					nimln_(142, "BFC.nim");
					T29_ = (NimStringDesc*)0;
					T29_ = rawNewString(7);
appendChar(T29_, word);
appendString(T29_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_44));
					result = T29_;
					goto BeforeRet_;
				}
				break;
				}
				nimln_(3661, "system.nim");
				TM_569c4PmJWUpENBqMXK119bZQ_60 = addInt(i, ((NI) 1));
				i = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_60);
				nimln_(3662, "system.nim");
				{
					if (!!(((code_2 ? code_2->Sup.len : 0) == L))) goto LA32_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_48));
				}
				LA32_: ;
			} LA3: ;
		}
	}
	nimln_(143, "BFC.nim");
	T34_ = (NimStringDesc*)0;
	T34_ = rawNewString(result_2->Sup.len + 11);
appendString(T34_, result_2);
appendString(T34_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_61));
	result = T34_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NimStringDesc*, generateCode_MOnda5xe8q9bWBsnOA9afp9aA)(NimStringDesc* code, NimStringDesc* lang) {
	NimStringDesc* result;
	nimfr_("generateCode", "BFC.nim");
{	result = (NimStringDesc*)0;
	nimln_(146, "BFC.nim");
	if (eqStrings(lang, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_62))) goto LA1_;
	goto LA2_;
	LA1_: ;
	{
		nimln_(148, "BFC.nim");
		result = generateCodeC_eCipD49bBoR7XjzCwo6ye8w_2(code);
		goto BeforeRet_;
	}
	goto LA3_;
	LA2_: ;
	{
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, writeToFile_O8j2V6DeDme1O9crQcbqBQg)(NimStringDesc* code, NimStringDesc* fileName) {
	FILE* file;
	nimfr_("writeToFile", "BFC.nim");
	nimln_(151, "BFC.nim");
	file = open_hqzpWQbdA2B8l9a6wwNoP4g(fileName, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 1), ((NI) -1));
	nimln_(152, "BFC.nim");
	write_c4mGyJBvK73pdM22jiweKQ(file, code);
	popFrame();
}

N_NIMCALL(NimStringDesc*, readFile_3HW0pLTpyB6rNH9c9bTGJJsA)(NimStringDesc* fileName) {
	NimStringDesc* result;
	NimStringDesc* result_2;
	FILE* file;
	nimfr_("readFile", "BFC.nim");
{	result = (NimStringDesc*)0;
	nimln_(155, "BFC.nim");
	result_2 = copyString(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_33));
	nimln_(156, "BFC.nim");
	file = open_hqzpWQbdA2B8l9a6wwNoP4g(fileName, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
	{
		NimStringDesc* line;
		NimStringDesc* res;
		line = (NimStringDesc*)0;
		nimln_(3230, "system.nim");
		res = rawNewString(((NI) 80));
		{
			nimln_(3231, "system.nim");
			while (1) {
				NIM_BOOL T4_;
				T4_ = (NIM_BOOL)0;
				T4_ = readLine_sO1bQXVRA6RP9cdYJXNKeSw(file, (&res));
				if (!T4_) goto LA3;
				line = res;
				nimln_(158, "BFC.nim");
				result_2 = resizeString(result_2, line->Sup.len + 0);
appendString(result_2, line);
			} LA3: ;
		}
	}
	nimln_(159, "BFC.nim");
	result = copyString(result_2);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_569c4PmJWUpENBqMXK119bZQ_63)(void) {
	nimGCvisit((void*)inputFileName_zB9b9b52qh3XkFGjYLZE2juA, 0);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, TM_569c4PmJWUpENBqMXK119bZQ_64)(void) {
	nimGCvisit((void*)outputFileName_ZhcyHRBNyFnZRHhCh8XN6Q, 0);
}
static N_NIMCALL(void, TM_569c4PmJWUpENBqMXK119bZQ_65)(void) {
	nimGCvisit((void*)lang_mHGi2iZeE3sD2KmUf2Yh7Q, 0);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(276, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(378, "system.nim");
		nimln_(276, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(277, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(278, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(279, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(378, "system.nim");
		nimln_(279, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(280, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(281, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(282, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	BFCDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	NimStringDesc* T23_;
	NimStringDesc* T24_;
	nimfr_("BFC", "BFC.nim");
nimRegisterGlobalMarker(TM_569c4PmJWUpENBqMXK119bZQ_63);
nimRegisterGlobalMarker(TM_569c4PmJWUpENBqMXK119bZQ_64);
nimRegisterGlobalMarker(TM_569c4PmJWUpENBqMXK119bZQ_65);
	nimln_(162, "BFC.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = inputFileName_zB9b9b52qh3XkFGjYLZE2juA; inputFileName_zB9b9b52qh3XkFGjYLZE2juA = copyStringRC1(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_33));
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(163, "BFC.nim");
	T2_ = (NimStringDesc*)0;
	T2_ = outputFileName_ZhcyHRBNyFnZRHhCh8XN6Q; outputFileName_ZhcyHRBNyFnZRHhCh8XN6Q = copyStringRC1(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_33));
	if (T2_) nimGCunrefNoCycle(T2_);
	nimln_(164, "BFC.nim");
	T3_ = (NimStringDesc*)0;
	T3_ = lang_mHGi2iZeE3sD2KmUf2Yh7Q; lang_mHGi2iZeE3sD2KmUf2Yh7Q = copyStringRC1(((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_62));
	if (T3_) nimGCunrefNoCycle(T3_);
	{
		NI colontmp_;
		NI res;
		colontmp_ = (NI)0;
		nimln_(165, "BFC.nim");
		colontmp_ = paramCount_T74rCHY8RMV0X07YnKmggw();
		nimln_(1986, "system.nim");
		res = ((NI) 1);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NimStringDesc* T7_;
				NI TM_569c4PmJWUpENBqMXK119bZQ_78;
				if (!(res <= colontmp_)) goto LA6;
				nimln_(1988, "system.nim");
				i_y9c9bTrpgLVFY29bwEqnXhzCg = res;
				nimln_(166, "BFC.nim");
				T7_ = (NimStringDesc*)0;
				T7_ = paramStr_eYicl3uwirn1ppNz7OCowg(i_y9c9bTrpgLVFY29bwEqnXhzCg);
				if (eqStrings(T7_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_66))) goto LA8_;
				if (eqStrings(T7_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_67))) goto LA9_;
				if (eqStrings(T7_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_68))) goto LA10_;
				if (eqStrings(T7_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_69))) goto LA11_;
				if (eqStrings(T7_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_70))) goto LA12_;
				if (eqStrings(T7_, ((NimStringDesc*) &TM_569c4PmJWUpENBqMXK119bZQ_71))) goto LA13_;
				goto LA14_;
				LA8_: ;
				{
					NI TM_569c4PmJWUpENBqMXK119bZQ_72;
					nimln_(168, "BFC.nim");
					TM_569c4PmJWUpENBqMXK119bZQ_72 = addInt(i_y9c9bTrpgLVFY29bwEqnXhzCg, ((NI) 1));
					asgnRefNoCycle((void**) (&inputFileName_zB9b9b52qh3XkFGjYLZE2juA), paramStr_eYicl3uwirn1ppNz7OCowg((NI)(TM_569c4PmJWUpENBqMXK119bZQ_72)));
				}
				goto LA15_;
				LA9_: ;
				{
					NI TM_569c4PmJWUpENBqMXK119bZQ_73;
					nimln_(170, "BFC.nim");
					TM_569c4PmJWUpENBqMXK119bZQ_73 = addInt(i_y9c9bTrpgLVFY29bwEqnXhzCg, ((NI) 1));
					asgnRefNoCycle((void**) (&inputFileName_zB9b9b52qh3XkFGjYLZE2juA), paramStr_eYicl3uwirn1ppNz7OCowg((NI)(TM_569c4PmJWUpENBqMXK119bZQ_73)));
				}
				goto LA15_;
				LA10_: ;
				{
					NI TM_569c4PmJWUpENBqMXK119bZQ_74;
					nimln_(172, "BFC.nim");
					TM_569c4PmJWUpENBqMXK119bZQ_74 = addInt(i_y9c9bTrpgLVFY29bwEqnXhzCg, ((NI) 1));
					asgnRefNoCycle((void**) (&outputFileName_ZhcyHRBNyFnZRHhCh8XN6Q), paramStr_eYicl3uwirn1ppNz7OCowg((NI)(TM_569c4PmJWUpENBqMXK119bZQ_74)));
				}
				goto LA15_;
				LA11_: ;
				{
					NI TM_569c4PmJWUpENBqMXK119bZQ_75;
					nimln_(174, "BFC.nim");
					TM_569c4PmJWUpENBqMXK119bZQ_75 = addInt(i_y9c9bTrpgLVFY29bwEqnXhzCg, ((NI) 1));
					asgnRefNoCycle((void**) (&outputFileName_ZhcyHRBNyFnZRHhCh8XN6Q), paramStr_eYicl3uwirn1ppNz7OCowg((NI)(TM_569c4PmJWUpENBqMXK119bZQ_75)));
				}
				goto LA15_;
				LA12_: ;
				{
					NI TM_569c4PmJWUpENBqMXK119bZQ_76;
					nimln_(176, "BFC.nim");
					TM_569c4PmJWUpENBqMXK119bZQ_76 = addInt(i_y9c9bTrpgLVFY29bwEqnXhzCg, ((NI) 1));
					asgnRefNoCycle((void**) (&lang_mHGi2iZeE3sD2KmUf2Yh7Q), paramStr_eYicl3uwirn1ppNz7OCowg((NI)(TM_569c4PmJWUpENBqMXK119bZQ_76)));
				}
				goto LA15_;
				LA13_: ;
				{
					NI TM_569c4PmJWUpENBqMXK119bZQ_77;
					nimln_(178, "BFC.nim");
					TM_569c4PmJWUpENBqMXK119bZQ_77 = addInt(i_y9c9bTrpgLVFY29bwEqnXhzCg, ((NI) 1));
					asgnRefNoCycle((void**) (&lang_mHGi2iZeE3sD2KmUf2Yh7Q), paramStr_eYicl3uwirn1ppNz7OCowg((NI)(TM_569c4PmJWUpENBqMXK119bZQ_77)));
				}
				goto LA15_;
				LA14_: ;
				{
				}
				LA15_: ;
				nimln_(1989, "system.nim");
				TM_569c4PmJWUpENBqMXK119bZQ_78 = addInt(res, ((NI) 1));
				res = (NI)(TM_569c4PmJWUpENBqMXK119bZQ_78);
			} LA6: ;
		}
	}
	nimln_(179, "BFC.nim");
	T23_ = (NimStringDesc*)0;
	T23_ = readFile_3HW0pLTpyB6rNH9c9bTGJJsA(inputFileName_zB9b9b52qh3XkFGjYLZE2juA);
	T24_ = (NimStringDesc*)0;
	T24_ = generateCode_MOnda5xe8q9bWBsnOA9afp9aA(T23_, lang_mHGi2iZeE3sD2KmUf2Yh7Q);
	writeToFile_O8j2V6DeDme1O9crQcbqBQg(T24_, outputFileName_ZhcyHRBNyFnZRHhCh8XN6Q);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, BFCDatInit000)(void) {
}

